[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
let g:everforest_background = 'hard'
let g:everforest_enable_italic = 1
let g:everforest_diagnostic_text_highlight = 1
let g:everforest_diagnostic_line_highlight = 0
let g:everforest_diagnostic_virtual_text = 'colored'
'''


[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
let g:gruvbox_material_background = 'soft'
let g:gruvbox_material_enable_italic = 1
let g:gruvbox_material_diagnostic_text_highlight = 1
let g:gruvbox_material_diagnostic_line_highlight = 0
let g:gruvbox_material_diagnostic_virtual_text = 'colored'
'''

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <leader>gs <cmd>tab Git<cr>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
        \ 'colorscheme': 'gruvbox_material',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'gitbranch', 'readonly', 'relativepath', 'modified' ] ]
        \ },
        \ 'component_function': {
        \   'gitbranch': 'FugitiveHead'
        \ },
        \ }
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'machakann/vim-textobj-delimited'

[[plugins]]
repo = 'vimwiki/vimwiki'
hook_add = '''
let g:vimwiki_list = [{ 'path': '~/Dropbox/wiki', 'syntax': 'markdown', 'ext': '.md' }, { 'path': './.wiki' }]
'''

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
let g:submode_timeout = v:false
'''
