[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
let g:everforest_background = 'hard'
let g:everforest_enable_italic = 1
let g:everforest_diagnostic_text_highlight = 1
let g:everforest_diagnostic_line_highlight = 0
let g:everforest_diagnostic_virtual_text = 'colored'
'''

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
nnoremap <leader>gs <cmd>Gina status<cr>
nnoremap <leader>gb <cmd>Gina branch<cr>
nnoremap <leader>gco<space> :Gina checkout<space>
nnoremap <leader>gci<space> :Gina commit<space>
nnoremap <leader>g<space> :Gina<space>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
        \ 'colorscheme': 'everforest',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
        \ },
        \ 'component_function': {
        \   'gitbranch': 'gina#component#repo#branch'
        \ },
        \ }
'''

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'machakann/vim-textobj-delimited'
