[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
buid = 'make'
on_ft = ['go']
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = "$GOPATH.'/bin/gocode'"
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']


# [[plugins]]
# repo = 'zchee/deoplete-jedi'
# on_ft = ['python']
# on_i = 1
# hook_add = '''
#   let g:deoplete#sources#jedi#show_docstring = 1
# '''
